### PR TITLE
Added ability to set button text from outside. 

### PR DESCRIPTION
**Pull request by zeusbaba**
This can be used to set localized text

### CODE REVIEW

**Comment by matthewroot** [comment]
@tomgilder Any chance you'd be willing to merge this PR, or implement a similar change yourself? We've been using your package in our app (thanks for making it!) and need to do some localization now. I spy localization on your TODO list and this is a simple way to enable any consumers of your package to localize the button text.

Thanks for you consideration.

**Comment by zeusbaba** [comment]
I implemented this small change as per need. Because my apps already has localisation, thus setting the text from the outside is very convenient.  
Feel free to use my fork till this PR gets merged or smt similar is implemented
```
apple_sign_in:
    git: git://github.com/beerstorm-net/flutter_apple_sign_in.git
```

**Comment by zeusbaba** [comment]
this repo is not maintained actively, and after Flutter2 release it will lag even more behind...    

I need this plugin and therefore I just created _a sister-project_ `the_apple_sign_in` which I'll actively maintain!  
If anyone is interested, welcome to use https://pub.dev/packages/the_apple_sign_in    
_p.s. pull requests and feedback are welcome!_

**Comment by tomgilder** [comment]
Hello. Sorry, yes, I haven't had time to maintain this project, and I haven't got a project that uses it to test with. 

@zeusbaba instead of creating another package name, would you like me to transfer ownership of this plugin and repo to you?

**Comment by zeusbaba** [comment]
> Hello. Sorry, yes, I haven't had time to maintain this project, and I haven't got a project that uses it to test with.
> 
> @zeusbaba instead of creating another package name, would you like me to transfer ownership of this plugin and repo to you?

thanks @tomgilder , that could be an option as well.  I have few concerns though.  
It has been almost 1 year with no response, that might have already negatively affected other developers....  
Would that be ok with you to flag this repo/plugin as `not-maintained / discontinued`?  

I've been using your plugin _(my own fork)_ with almost every Flutter App I develop/publish. Therefore, I would prefer spending my energy on the newly created [the_apple_sign_in](https://github.com/beerstorm-net/the_apple_sign_in) as _sister-project_ built based on your efforts.

**Comment by tomgilder** [comment]
@zeusbaba done. Marked as discontinued and GitHub repo updated. Thanks for taking this on and good luck with it :-)

**Pull request closed without merging**
